tracer.property: "I AM THE DEV VERSION"
example.property: "I AM THE DEV VERSION"
spring:
  jpa:
    databaseplatform: org.hibernate.dialect.H2Dialect
    showsql: true
    hibernate:
      ddlauto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        dialect: "org.hibernate.dialect.H2Dialect"
  datasource:
    platform: "h2"
    url: "jdbc:h2:mem:exampleapp;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    username: "sa"
    password:
  database:
    driverClassName: "org.h2.Driver"
redis:
  server: "redis"
  port: "6379"
signing:
  key: "345345fsdfsf5345"

  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        weballowothers: false
